apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-container
            image: busybox
            command: ["sh", "-c", "/config/script.sh"]
            volumeMounts:
            - name: script-volume
              mountPath: /config
          volumes:
          - name: script-volume
            configMap:
              name: my-script-config
              defaultMode: 0775
          restartPolicy: OnFailure
